### ISSUE TITLE
Get binder working again

### ISSUE THREAD

**Issue by rsignell-usgs** [reproducible-notebooks/ERDDAP_timeseries_explorer#8]
Currently if I click the binder link and run the notebook it fails loading some erddapy stuff.  I'm guessing it moved. 

![2020-11-17_10-25-36](https://user-images.githubusercontent.com/1872600/99409505-757e2d00-28bf-11eb-8b86-57a74e992309.png)

@apkrelling , hoping you can take a look, perhaps with the help of @ocefpaf

**Comment by ocefpaf** [comment]
The author of erddapy made a major refactor and released a minor version instead of major. Quite the amateurish package and we should not use it :stuck_out_tongue_closed_eyes: 

@apkrelling most of the relevant changes are in https://github.com/ioos/erddapy/pull/145. The submodules moved a bit and `utilities` no longer exists. So we need to import `urlopen` from `erddapy.url_handling` now. Do you want to send a PR to fix that?

**Comment by apkrelling** [comment]
Fixed in c15e11cc607ee0ceffc8b47ff163531ff26039ae (.py) and 14508b7ef04afd5c990f32e7f3ba9501eab479d9 (.ipynb).
